dist: bionic
language: ruby
gemfile:
  - Gemfile
services:
  - postgresql
  - redis-server
addons:
  postgresql: 10
script: bundle exec rake test
before_install:
  - createdb searchkick_test || true
  - ./test/ci/install_elasticsearch.sh
cache:
  directories:
    - $HOME/elasticsearch
env:
  - ELASTICSEARCH_VERSION=7.6.1
jdk: openjdk10
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
      env: ELASTICSEARCH_VERSION=7.0.0
    - rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
      env: ELASTICSEARCH_VERSION=6.8.7
    - rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
      env: ELASTICSEARCH_VERSION=6.0.0
    - rvm: 2.7
      gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
        - redis-server
    - rvm: 2.6
      gemfile: test/gemfiles/mongoid6.gemfile
      services:
        - mongodb
        - redis-server
notifications:
  email:
    on_success: never
    on_failure: change
