sudo: false
language: ruby
rvm: 2.3.1
services:
  - mongodb
  - redis-server
before_install:
  - ./test/ci/before_install.sh
script: bundle exec rake test
before_script:
  - psql -c 'create database searchkick_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
  - test/gemfiles/mongoid5.gemfile
  - test/gemfiles/mongoid6.gemfile
env:
  - ELASTICSEARCH_VERSION=5.4.0
jdk: oraclejdk8
matrix:
  include:
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=2.0.0
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=2.4.3
      jdk: oraclejdk7
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=5.0.1
      jdk: oraclejdk8
