language: ruby
rvm:
  - 1.9.3
  - 2.0.0
services:
  - elasticsearch
  - mongodb
script: bundle exec rake test
before_script:
  - psql -c 'create database searchkick_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile