language: ruby
rvm: 2.2
services:
  - elasticsearch
  - mongodb
before_install:
  - ./test/ci/before_install.sh
script: RUBYOPT=W0 bundle exec rake test
before_script:
  - psql -c 'create database searchkick_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord41.gemfile
  - test/gemfiles/activerecord40.gemfile
  - test/gemfiles/activerecord32.gemfile
  - test/gemfiles/activerecord31.gemfile
  - test/gemfiles/mongoid2.gemfile
  - test/gemfiles/mongoid3.gemfile
  - test/gemfiles/mongoid4.gemfile
  - test/gemfiles/mongoid5.gemfile
env:
  - ELASTICSEARCH_VERSION=2.3.0
matrix:
  include:
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=1.0.0
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=1.7.0
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=2.0.0
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=5.0.0-alpha2
    # - gemfile: test/gemfiles/nobrainer.gemfile
    #   env: NOBRAINER=true
  allow_failures:
    - gemfile: Gemfile
      env: ELASTICSEARCH_VERSION=5.0.0-alpha2
    # - gemfile: test/gemfiles/nobrainer.gemfile
    #   env: NOBRAINER=true
