dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
services:
  - postgresql
  - redis-server
script: bundle exec rake test
before_install:
  - createdb searchkick_test || true
  - ./test/ci/install_elasticsearch.sh
cache:
  directories:
    - $HOME/elasticsearch
env:
  - ELASTICSEARCH_VERSION=7.3.2
jdk: openjdk10
matrix:
  include:
    - gemfile: Gemfile
    - gemfile: test/gemfiles/activerecord52.gemfile
      env: ELASTICSEARCH_VERSION=7.0.0
    - gemfile: test/gemfiles/activerecord51.gemfile
      env: ELASTICSEARCH_VERSION=6.8.3
    - gemfile: test/gemfiles/activerecord50.gemfile
      env: ELASTICSEARCH_VERSION=6.0.0
    - gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
        - redis-server
    - gemfile: test/gemfiles/mongoid6.gemfile
      services:
        - mongodb
        - redis-server
notifications:
  email:
    on_success: never
    on_failure: change
