language: ruby
rvm:
  - 2.2
services:
  - elasticsearch
  - mongodb
before_install:
  - ./ci/before_install.sh
script: bundle exec rake test
before_script:
  - psql -c 'create database searchkick_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - gemfiles/activerecord41.gemfile
  - gemfiles/activerecord40.gemfile
  - gemfiles/activerecord32.gemfile
  - gemfiles/activerecord31.gemfile
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/mongoid4.gemfile
matrix:
  include:
    - gemfile: gemfiles/nobrainer.gemfile
      env: NOBRAINER=true
